version: '1.0.0'
services:
  backend:
    build: backend
    ports:
      - 8081:8080
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
#      POSTGRES_DB: postgres
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    expose:
      - 5432
volumes:
  db:
    driver: local