spring:
  application:
    name: simple-web-server
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres:postgres@db:5432/postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
